blank_issues_enabled: false
contact_links:
    - name: Ask Question
      url: https://github.com/eryx12o45/react-supabase-next/discussions
      about: Ask questions and discuss with other community members
